<?php

return [
    'areas' => [
        [
            'name' => '北海道・東北',
            'code' => 'hokkaido-tohoku',
            'name_kana' => 'ほっかいどう・とうほく',
            'name_en' => 'Hokkaido & Tohoku',
            'order' => 1,
        ],
        [
            'name' => '関東',
            'code' => 'kanto',
            'name_kana' => 'かんとう',
            'name_en' => 'Kanto',
            'order' => 2,
        ],
        [
            'name' => '中部',
            'code' => 'chubu',
            'name_kana' => 'ちゅうぶ',
            'name_en' => 'Chubu',
            'order' => 3,
        ],
        [
            'name' => '近畿',
            'code' => 'kinki',
            'name_kana' => 'きんき',
            'name_en' => 'Kinki',
            'order' => 4,
        ],
        [
            'name' => '中国・四国',
            'code' => 'chugoku-shikoku',
            'name_kana' => 'ちゅうごく・しこく',
            'name_en' => 'Chugoku & Shikoku',
            'order' => 5,
        ],
        [
            'name' => '九州・沖縄',
            'code' => 'kyushu-okinawa',
            'name_kana' => 'きゅうしゅう・おきなわ',
            'name_en' => 'Kyushu & Okinawa',
            'order' => 6,
        ],
    ],
    'prefectures' => [
        ['japan_area_id' => 1, 'code' => 1, 'name' => '北海道', 'name_kana' => 'ほっかいどう', 'name_en' => 'Hokkaido', 'order' => 1],
        ['japan_area_id' => 1, 'code' => 2, 'name' => '青森県', 'name_kana' => 'あおもりけん', 'name_en' => 'Aomori', 'order' => 2],
        ['japan_area_id' => 1, 'code' => 3, 'name' => '岩手県', 'name_kana' => 'いわてけん', 'name_en' => 'Iwate', 'order' => 3],
        ['japan_area_id' => 1, 'code' => 4, 'name' => '宮城県', 'name_kana' => 'みやぎけん', 'name_en' => 'Miyagi', 'order' => 4],
        ['japan_area_id' => 1, 'code' => 5, 'name' => '秋田県', 'name_kana' => 'あきたけん', 'name_en' => 'Akita', 'order' => 5],
        ['japan_area_id' => 1, 'code' => 6, 'name' => '山形県', 'name_kana' => 'やまがたけん', 'name_en' => 'Yamagata', 'order' => 6],
        ['japan_area_id' => 1, 'code' => 7, 'name' => '福島県', 'name_kana' => 'ふくしまけん', 'name_en' => 'Fukushima', 'order' => 7],
        ['japan_area_id' => 2, 'code' => 8, 'name' => '茨城県', 'name_kana' => 'いばらきけん', 'name_en' => 'Ibaraki', 'order' => 8],
        ['japan_area_id' => 2, 'code' => 9, 'name' => '栃木県', 'name_kana' => 'とちぎけん', 'name_en' => 'Tochigi', 'order' => 9],
        ['japan_area_id' => 2, 'code' => 10, 'name' => '群馬県', 'name_kana' => 'ぐんまけん', 'name_en' => 'Gunma', 'order' => 10],
        ['japan_area_id' => 2, 'code' => 11, 'name' => '埼玉県', 'name_kana' => 'さいたまけん', 'name_en' => 'Saitama', 'order' => 11],
        ['japan_area_id' => 2, 'code' => 12, 'name' => '千葉県', 'name_kana' => 'ちばけん', 'name_en' => 'Chiba', 'order' => 12],
        ['japan_area_id' => 2, 'code' => 13, 'name' => '東京都', 'name_kana' => 'とうきょうと', 'name_en' => 'Tokyo', 'order' => 13],
        ['japan_area_id' => 2, 'code' => 14, 'name' => '神奈川県', 'name_kana' => 'かながわけん', 'name_en' => 'Kanagawa', 'order' => 14],
        ['japan_area_id' => 3, 'code' => 15, 'name' => '新潟県', 'name_kana' => 'にいがたけん', 'name_en' => 'Niigata', 'order' => 15],
        ['japan_area_id' => 3, 'code' => 16, 'name' => '富山県', 'name_kana' => 'とやまけん', 'name_en' => 'Toyama', 'order' => 16],
        ['japan_area_id' => 3, 'code' => 17, 'name' => '石川県', 'name_kana' => 'いしかわけん', 'name_en' => 'Ishikawa', 'order' => 17],
        ['japan_area_id' => 3, 'code' => 18, 'name' => '福井県', 'name_kana' => 'ふくいけん', 'name_en' => 'Fukui', 'order' => 18],
        ['japan_area_id' => 3, 'code' => 19, 'name' => '山梨県', 'name_kana' => 'やまなしけん', 'name_en' => 'Yamanashi', 'order' => 19],
        ['japan_area_id' => 3, 'code' => 20, 'name' => '長野県', 'name_kana' => 'ながのけん', 'name_en' => 'Nagano', 'order' => 20],
        ['japan_area_id' => 3, 'code' => 21, 'name' => '岐阜県', 'name_kana' => 'ぎふけん', 'name_en' => 'Gifu', 'order' => 21],
        ['japan_area_id' => 3, 'code' => 22, 'name' => '静岡県', 'name_kana' => 'しずおかけん', 'name_en' => 'Shizuoka', 'order' => 22],
        ['japan_area_id' => 3, 'code' => 23, 'name' => '愛知県', 'name_kana' => 'あいちけん', 'name_en' => 'Aichi', 'order' => 23],
        ['japan_area_id' => 4, 'code' => 24, 'name' => '三重県', 'name_kana' => 'みえけん', 'name_en' => 'Mie', 'order' => 24],
        ['japan_area_id' => 4, 'code' => 25, 'name' => '滋賀県', 'name_kana' => 'しがけん', 'name_en' => 'Shiga', 'order' => 25],
        ['japan_area_id' => 4, 'code' => 26, 'name' => '京都府', 'name_kana' => 'きょうとふ', 'name_en' => 'Kyoto', 'order' => 26],
        ['japan_area_id' => 4, 'code' => 27, 'name' => '大阪府', 'name_kana' => 'おおさかふ', 'name_en' => 'Osaka', 'order' => 27],
        ['japan_area_id' => 4, 'code' => 28, 'name' => '兵庫県', 'name_kana' => 'ひょうごけん', 'name_en' => 'Hyogo', 'order' => 28],
        ['japan_area_id' => 4, 'code' => 29, 'name' => '奈良県', 'name_kana' => 'ならけん', 'name_en' => 'Nara', 'order' => 29],
        ['japan_area_id' => 4, 'code' => 30, 'name' => '和歌山県', 'name_kana' => 'わかやまけん', 'name_en' => 'Wakayama', 'order' => 30],
        ['japan_area_id' => 5, 'code' => 31, 'name' => '鳥取県', 'name_kana' => 'とっとりけん', 'name_en' => 'Tottori', 'order' => 31],
        ['japan_area_id' => 5, 'code' => 32, 'name' => '島根県', 'name_kana' => 'しまねけん', 'name_en' => 'Shimane', 'order' => 32],
        ['japan_area_id' => 5, 'code' => 33, 'name' => '岡山県', 'name_kana' => 'おかやまけん', 'name_en' => 'Okayama', 'order' => 33],
        ['japan_area_id' => 5, 'code' => 34, 'name' => '広島県', 'name_kana' => 'ひろしまけん', 'name_en' => 'Hiroshima', 'order' => 34],
        ['japan_area_id' => 5, 'code' => 35, 'name' => '山口県', 'name_kana' => 'やまぐちけん', 'name_en' => 'Yamaguchi', 'order' => 35],
        ['japan_area_id' => 5, 'code' => 36, 'name' => '徳島県', 'name_kana' => 'とくしまけん', 'name_en' => 'Tokushima', 'order' => 36],
        ['japan_area_id' => 5, 'code' => 37, 'name' => '香川県', 'name_kana' => 'かがわけん', 'name_en' => 'Kagawa', 'order' => 37],
        ['japan_area_id' => 5, 'code' => 38, 'name' => '愛媛県', 'name_kana' => 'えひめけん', 'name_en' => 'Ehime', 'order' => 38],
        ['japan_area_id' => 5, 'code' => 39, 'name' => '高知県', 'name_kana' => 'こうちけん', 'name_en' => 'Kochi', 'order' => 39],
        ['japan_area_id' => 6, 'code' => 40, 'name' => '福岡県', 'name_kana' => 'ふくおかけん', 'name_en' => 'Fukuoka', 'order' => 40],
        ['japan_area_id' => 6, 'code' => 41, 'name' => '佐賀県', 'name_kana' => 'さがけん', 'name_en' => 'Saga', 'order' => 41],
        ['japan_area_id' => 6, 'code' => 42, 'name' => '長崎県', 'name_kana' => 'ながさきけん', 'name_en' => 'Nagasaki', 'order' => 42],
        ['japan_area_id' => 6, 'code' => 43, 'name' => '熊本県', 'name_kana' => 'くまもとけん', 'name_en' => 'Kumamoto', 'order' => 43],
        ['japan_area_id' => 6, 'code' => 44, 'name' => '大分県', 'name_kana' => 'おおいたけん', 'name_en' => 'Oita', 'order' => 44],
        ['japan_area_id' => 6, 'code' => 45, 'name' => '宮崎県', 'name_kana' => 'みやざきけん', 'name_en' => 'Miyazaki', 'order' => 45],
        ['japan_area_id' => 6, 'code' => 46, 'name' => '鹿児島県', 'name_kana' => 'かごしまけん', 'name_en' => 'Kagoshima', 'order' => 46],
        ['japan_area_id' => 6, 'code' => 47, 'name' => '沖縄県', 'name_kana' => 'おきなわけん', 'name_en' => 'Okinawa', 'order' => 47],
    ],
];
